### ISSUE TITLE
Using Promises instead of callbacks

### ISSUE THREAD

**Issue by Eric-Arellano** [mbirkegaard/basic-crud#2]
Hello, thank you so much for open sourcing this project! It was invaluable to me learning how to bind to Auth0.js in my app. 

While working on my project's implementation, I recently wrapped Auth0's use of callbacks in promises, because promises are so much easier and desirable to understand. I'd love to upstream those changes to your project if you'd be interested?

**Comment by mbirkegaard** [comment]
Hi Eric,

You're welcome! I'm happy to hear that it was useful.

I do prefer Promises over callbacks, so please do a PR and I'll merge. Thanks!
